# Resolve react_native_pods.rb with node to allow for hoisting
require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'taxi' do
  # Add use_frameworks with static linkage
  use_frameworks! :linkage => :static

  # # ✅ Firebase 관련 패키지 정리
  # pod 'Firebase/Analytics'
  # pod 'Firebase/Messaging'
  # pod 'RNFBApp', :path => '../node_modules/@react-native-firebase/app'

  # ✅ Google Maps 관련 패키지 정리
  pod 'GoogleMaps'
  pod 'GooglePlaces', '9.2.0'
  pod 'GooglePlacesSwift', '0.3.0'
  pod 'Google-Maps-iOS-Utils', '5.0.0'

  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path

  # ✅ `use_native_modules!` 먼저 실행
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
    )
     # ✅ GoogleUtilities 모듈 헤더 적용 (오류 해결)
     installer.pods_project.targets.each do |target|
      if target.name == 'GoogleUtilities'
        target.build_configurations.each do |config|
          config.build_settings['DEFINES_MODULE'] = 'YES'
        end
      end
    end
  end
end
